### ISSUE TITLE
Issue on PhpBB 3.3.5

### ISSUE THREAD

**Issue by FN-TUDA** [Getekid/phpbb3-CAS-Auth-plugin#23]
Hi,
thank you for developing this plugin.

Unfortunately I wasn't able to install it on PhPBB 3.3.5.
After uploading the folders (including CAS) and enabling the extension, I get the following fatal error when accessing ACP > General > Client Communication > Authentication:

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'getekid\\cas\\auth\\provider\\cas' not found in /var/www/vhosts/servername/httpdocs/forum/cache/production/container_dbdbe80dc7030ae9bd39ee30cca82130.php:999\nStack trace:\n#0 /var/www/vhosts/servername/httpdocs/forum/vendor/symfony/dependency-injection/Container.php(306): phpbb_cache_container->getAuth_Provider_CasService()\n#1 /var/www/vhosts/servername/httpdocs/forum/phpbb/di/service_collection.php(57): Symfony\\Component\\DependencyInjection\\Container->get()\n#2 /var/www/vhosts/sservername/httpdocs/forum/phpbb/di/service_collection_iterator.php(44): phpbb\\di\\service_collection->offsetGet()\n#3 /var/www/vhosts/servername/httpdocs/forum/includes/acp/acp_board.php(649): phpbb\\di\\service_collection_iterator->current()\n#4 /var/www/vhosts/servername/httpdocs/forum/includes/functions_module.php(676): acp_board->main()\n#5 /var/www/vhosts/servername...', referer: https://servername/forum/adm/index.php?sid=1520d7fb543ba3e863938c8581b045fe&i=1

any suggestion about how I might fix this?
Thanks
Francesco

**Comment by Getekid** [comment]
Hello Francesco, glad this could be useful to you.

Have you tried to purge the cache after installing the extension? If not please do so and let me know if the error persists.

Cheers

**Comment by FN-TUDA** [comment]
Thanks for the suggestion. 
I purged the cash (both from the ACP and manually by erasing the content of the Cache subfolder) but the error "AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'getekid\\cas\\auth\\provider\\cas' not found..." unfortunately still persists.
I'm using phpBB 3.3.5 w/PHP 7.4.26.

**Comment by Getekid** [comment]
Hello again, sorry for the delay but I just managed to have a look.

I had a fresh install of phpBB 3.3.5 and the extension loaded without any issues.
Can you ensure that the file `root/ext/getekid/cas/auth/provider/cas.php` exists and is readable from the server?
